config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/subjects/search' => 'subjects#search'

  get '/subjects/:id/alert' => 'subjects#alert'

  get '/subjects/:subject_id/reviews/alert' => 'reviews#alert'

  resources :users, only: :show
  resources :subjects do
    resources :maps, only: [:new, :create]
    resources :reviews, except: [:destroy]
  end

  resources :images, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  root 'subjects#index'

end

app/models/exposure.rb
class Exposure < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :user
  belongs_to :subject
  belongs_to :review
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  accepts_nested_attributes_for :subject
  accepts_nested_attributes_for :review

  mount_uploader :image_file, ImageFileUploader

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :image, counter_cache: :likes_count
  belongs_to :user
end

app/models/map.rb
class Map < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode

  belongs_to :subject
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject
  has_many :images
  belongs_to :map

  accepts_nested_attributes_for :subject
  accepts_nested_attributes_for :images
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user
  has_many :images
  has_many :reviews

  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :reviews

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :subjects
  has_many :images

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    '/users/sign_in'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  layout 'review_site'
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, image_id: params[:image_id])
    @image = @like.image
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, image_id: params[:image_id])
    @image = like.image
    like.destroy
    @image.likes_count -= 1
  end

end

app/controllers/maps_controller.rb
class MapsController < LayoutsController

  def new
    @map = Map.find_by(subject_id: params[:id])
    @hash = Gmaps4rails.build_markers(@map) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
    end

    @prefecture = Subject.find(params[:subject_id])
  end

  def create
    @map = Map.create(create_params)
    @subject = Subject.find(@map.subject_id)
  end

  private
  def create_params
    params.permit(
      :latitude,
      :longitude
      ).merge(subject_id: params[:subject_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < LayoutsController
  before_action :authenticate_user!, except: :index

  def index
    redirect_to controller: :subjects, action: :index
  end

  def edit
    @subject = Subject.find(params[:subject_id])
    @review = Review.find(params[:id])
    @images = @review.images
    @exposures = Exposure.all
  end

  def update
  end

  def alert
    @review = Review.find_by(user_id: current_user.id)
  end

  def new
    @subject = Subject.find(params[:subject_id])

    if @subject.reviews.where(user_id: current_user.id).present?
      redirect_to controller: :reviews, action: :alert
    else

    @review = Review.new
    @review.images.build
    # @review.build_image
    @exposures = Exposure.all
  end
  end

  def create
    review = Review.create(create_params)
    images = Image.where(review_id: review.id)

    #Imageテーブルのsubject_idとuser_idに値を代入
    images.update_all(subject_id: params[:subject_id], user_id: current_user.id)
  end
end

private
  def create_params
    params.require(:review).permit(
      :rate,
      :num_rate,
      :challenge_rate,
      :envir_rate,
      :access_rate,
      :comment,
      images_attributes:[
      :image_file,
      :f_value,
      :exposure,
      :wb,
      :title,
      :comment,
      :image_file2,
      :f_value2,
      :exposure2,
      :wb2,
      :title2,
      :comment2,
      :image_file3,
      :f_value3,
      :exposure3,
      :wb3,
      :title3,
      :comment3,
      ]).merge(subject_id: params[:subject_id], user_id: current_user.id)
  end

app/controllers/subjects_controller.rb
class SubjectsController < LayoutsController
  before_action :authenticate_user!, only: :new

  def index
    subjects_ids = Review.group(:subject_id).order('count_subject_id DESC').limit(20).count(:subject_id).keys
    @subjects = subjects_ids.map{|id| Subject.find(id)}
  end

  def search
    @subjects = Subject.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

  def alert
    @subject = Subject.find(params[:id])
  end

  def show
    @subject = Subject.find(params[:id])
    @map = Map.find_by(subject_id: params[:id])
    @hash = Gmaps4rails.build_markers(@map) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
    end
  end

  def new
    @subject = Subject.new
    @prefectures = Prefecture.all
    @exposures = Exposure.all
  end

  def create
    if Subject.where(name: params.require(:subject).permit(:name)[:name]).present?
      subject = Subject.find_by(name: params.require(:subject).permit(:name)[:name])
      redirect_to "/subjects/#{subject.id}/alert"
    else

    Subject.create(create_params)
    redirect_to "/subjects/#{@subject.id}/maps/new"
  end
  end

  private
  def create_params
    params.require(:subject).permit(
      :name,
      :prefecture
      ).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OriginalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/review_site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OriginalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyBRCB2MqZELwZgH6Ix1O0QYD7KLf4jlSTU"></script>
<script src='//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js'></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ふぉと場所</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <%= form_tag('/subjects/search', method: :get, class: "navbar-form navbar-left") do %>
          <div class="form-group">
            <input name="keyword" type="text" class="form-control" placeholder="キーワードで検索">
      </div>
            <button type="submit" class="btn btn-default">Submit</button>
        <% end %>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "サインアウト", "/users/sign_out", method: :delete %>
          </li>
          <li>
            <a href="/users/<%= current_user.id %>">マイページ</a>
          </li>
        <% else %>
          <li>
            <a href="/users/sign_in">ログイン</a>
          </li>
          <li>
            <a href="/users/sign_up">新規登録</a>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/likes/create.js.erb
$("#like-function-<%= @image.id %>").html("<%= j(render '/subjects/like', image: @image) %>");

app/views/likes/destroy.js.erb
$("#like-function-<%= @image.id %>").html("<%= j(render '/subjects/like', image: @image) %>");

app/views/maps/create.html.erb
<h2>
  被写体の登録が完了しました！
</h2>
</br>
</br>
<%= link_to "登録した被写体を評価する", new_subject_review_path(@subject) %>
</br>
</br>
<%= link_to "この被写体のページへ", subject_path(@subject) %>
</br>
</br>
<a href="/">TOPページへ</a>

app/views/maps/new.html.erb
<form action="#" onsubmit="getLatLng(document.getElementById('address').value); return(false);">
  地名:
    <input type="text" id="address" style="width: 400px" value>
    <input type="submit" value="検索">
</form>

<p>
  住所で検索されますと、より正確な結果が得られます。</br>
  ※市区町村レベルの大雑把な住所でも、範囲を絞り込めます。
</p>

</br>
</br>

<p>
  撮影スポットにピンを立ててください。
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px; position: relative; overflow: hidden;'></div>
</div>

<p>
  ピンを立てたら、登録ボタンを押してください。
</p>


<script type="text/javascript">

var markersArray = [];

var map = new google.maps.Map(document.getElementById("map"),{
  zoom: 7,
  center: new google.maps.LatLng(36,138),
  clickableIcons: false,
});

function getLatLng(place) {

  // ジオコーダのコンストラクタ
  var geocoder = new google.maps.Geocoder();

  // geocodeリクエストを実行。
  // 第１引数はGeocoderRequest。住所⇒緯度経度座標の変換時はaddressプロパティを入れればOK。
  // 第２引数はコールバック関数。
  geocoder.geocode({
    address: place
  }, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {

      // 結果の表示範囲。結果が１つとは限らないので、LatLngBoundsで用意。
      var bounds = new google.maps.LatLngBounds();

      for (var i in results) {
        if (results[i].geometry) {

          // 緯度経度を取得
          var latlng = results[i].geometry.location;

          // 住所を取得(日本の場合だけ「日本, 」を削除)
          var address = results[i].formatted_address.replace(/^日本, /, '');

          // 検索結果地が含まれるように範囲を拡大
          bounds.extend(latlng);

          marker = new google.maps.Marker({
            position: latlng,
            map: map
          });

          document.getElementById('lat').value = latlng.lat();
          document.getElementById('lng').value = latlng.lng();

          markersArray.push(marker);

        }
      }

          // あとはご自由に・・・。
          google.maps.event.addListener(map, 'click', function(event){
              clearMarker();
              getClickLatLng(event.latLng, map);
              });
          };

          function clearMarker(){
            for(var i = 0; i < markersArray.length; i++){
              markersArray[i].setMap(null);
            }
          }

          function getClickLatLng(lat_lng, map){

            document.getElementById('lat').value = lat_lng.lat();
            document.getElementById('lng').value = lat_lng.lng();


          var marker = new google.maps.Marker({
                  position: lat_lng,
                  map: map,
          });
          markersArray.push(marker);
        }


      // 範囲を移動
      map.fitBounds(bounds);
    });
  };
</script>


<%= form_tag("/subjects/#{params[:subject_id]}/maps", method: :post) do %>
  <input type="text" id="lat" name="latitude" style="display: none" value="">
  <input type="text" id="lng" name="longitude" style="display: none" value="">
  <input type="submit" value="登録">
<% end %>

app/views/reviews/alert.html.erb
<p>
  同じ被写体に複数回レビューを投稿することはできません
</p>
<br>
<%= link_to '投稿済みのレビューを修正する', "/subjects/#{params[:subject_id]}/reviews/#{@review.id}/edit" %>

app/views/reviews/create.html.erb
<p>
  投稿が完了しました
</p>
</br>
</br>
<a href="/">TOP PAGE</a>

app/views/reviews/edit.html.erb
<%= form_for [@subject, @review] do |f| %>
    <h3>
      編集する
    </h3>
    <%= f.label :星いくつ？（5点満点） %>
  <%= f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1, value: @review.rate %>
  <%= f.label :理由などをコメントしてください %>
  <%= f.text_field :comment, placeholder: 'コメントを入力', value: @review.comment %>
    </br>
    </br>
    <%= f.fields_for :images, @images do |image| %>
      <%= image.label :画像ファイル %>
      <%= image.file_field :image_file %>
      <%= image.label :f値 %>
      <%= image.text_field :f_value, placeholder: "f値を入力（任意）" %>
      <%= image.label :露出 %>
      <%= image.select :exposure, @exposures.map{|exp| exp.num}, placeholder: "露出を選択（任意）" %>
      <%= image.label :ホワイトバランス %>
      <%= image.text_field :wb %>
      <%= image.label :写真にタイトルをつけてください（任意） %>
      <%= image.text_field :title, placeholder: "タイトルを入力" %>
      <%= image.label :写真について、コメントをお書きください（任意） %>
      <%= image.text_field :comment, placeholder: "コメントを入力" %>
    </br>
    </br>
  <% end %>
    </br>
    </br>
    <%= f.submit "修正" %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@subject, @review] do |f| %>
  <%= f.label :総合評価（5点満点） %>
  <%= f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1 %>
  <%= f.label :被写体の数量（5点満点） %>
  <%= f.number_field :num_rate, placeholder: '評価', value: 1, max: 5, min: 1 %>
  <%= f.label :撮影難易度（5点満点） %>
  <%= f.number_field :challenge_rate, placeholder: '評価', value: 1, max: 5, min: 1 %>
  <%= f.label :撮影環境（5点満点） %>
  <%= f.number_field :envir_rate, placeholder: '評価', value: 1, max: 5, min: 1 %>
  <%= f.label :アクセスの良さ（5点満点） %>
  <%= f.number_field :access_rate, placeholder: '評価', value: 1, max: 5, min: 1 %>
  <%= f.label :評価の理由などをコメントしてください %>
  <%= f.text_field :comment, placeholder: 'コメントを入力' %>



  <%= f.fields_for :images do |image| %>
    <%= image.label :この被写体の写真を3つまで投稿できます %>
    <%= image.file_field :image_file %>
    <%= image.text_field :f_value, placeholder: "f値を入力（任意）" %>
    <%= image.select :exposure, @exposures.map{|exp| exp.num}, placeholder: "露出を選択（任意）" %>
    <%= image.text_field :wb, placeholder: "ホワイトバランスを入力してください（任意）" %>
    <%= image.label :写真にタイトルをつけてください（任意） %>
    <%= image.text_field :title, placeholder: "タイトルを入力" %>
    <%= image.label :写真について、コメントをお書きください（任意） %>
    <%= image.text_field :comment, placeholder: "コメントを入力" %>
  <% end %>


  <%= f.fields_for :images do |image| %>
    <%= image.file_field :image_file %>
    <%= image.text_field :f_value, placeholder: "f値を入力（任意）" %>
    <%= image.select :exposure, @exposures.map{|exp| exp.num}, placeholder: "露出を選択（任意）", value: "0.0" %>
    <%= image.text_field :wb, placeholder: "ホワイトバランスを入力してください（任意）" %>
    <%= image.label :写真にタイトルをつけてください（任意） %>
    <%= image.text_field :title, placeholder: "タイトルを入力" %>
    <%= image.label :写真について、コメントをお書きください（任意） %>
    <%= image.text_field :comment, placeholder: "コメントを入力" %>
  <% end %>


  <%= f.fields_for :images do |image| %>
    <%= image.file_field :image_file %>
    <%= image.text_field :f_value, placeholder: "f値を入力（任意）" %>
    <%= image.select :exposure, @exposures.map{|exp| exp.num}, placeholder: "露出を選択（任意）" %>
    <%= image.text_field :wb, placeholder: "ホワイトバランスを入力してください（任意）" %>
    <%= image.label :写真にタイトルをつけてください（任意） %>
    <%= image.text_field :title, placeholder: "タイトルを入力" %>
    <%= image.label :写真について、コメントをお書きください（任意） %>
    <%= image.text_field :comment, placeholder: "コメントを入力" %>
  <% end %>



  <%= f.submit "投稿する" %>
<% end %>

app/views/reviews/show.html.erb
<p>
  Hello World
</p>

app/views/reviews/update.html.erb
<p>
  修正が完了しました
</p>
</br>
</br>
<a href="/">TOP PAGE</a>

app/views/subjects/_image.html.erb
<% if image.image_file.present? %>
  <%= image_tag image.image_file.url %>
  <div id="like-function-<%= image.id %>">
  <%= render "like", image: image %>
  </div>
  <!-- image_file.present?の閉じタグ -->
  <% end %>

  <br>

</li>

app/views/subjects/_like.html.erb
<% if user_signed_in? %>
  <!-- ログインユーザーがすでにいいね！している場合 -->
  <% if image.like_user(current_user.id) %>
      <%= button_to "/images/#{image.id}/likes/#{image.likes.find_by(user_id: current_user.id).id}", method: :delete, id: "like-button", remote: true do %>
        <div><i class="glyphicon glyphicon-thumbs-up"></i></div>
        <span>
          <%= image.likes_count %>
        </span>
      <% end %>
  <!-- ログインユーザーが未だいいね！をしていない場合 -->
  <% else %>
    <%= button_to "/images/#{image.id}/likes", id: "like-button", remote: true do %>
      <div><span class="glyphicon glyphicon-thumbs-up"></span></div>
      <span>
        <%= image.likes_count %>
      </span>
    <% end %>

  <!-- image.like_user(current_user.id)の閉じタグ -->
  <% end %>

<!-- user_signed_inのelseタグ -->
<% else %>

  <div><i class="glyphicon glyphicon-thumbs-up"></i></div>
  <span>
    <%= image.likes_count %>
  </span>

<!-- user_signed_in?の閉じタグ -->
<% end %>

app/views/subjects/_review.html.erb
  <li style="border-bottom: dotted 1px">
      <h3>
        <%= review.user.nickname %>
      </h3>
      <span class="rate rate<%= review.rate %>0"></span>
      <p>
        <%= review.comment %>
      </p>
        <%= render partial: "image", collection: review.images %>

app/views/subjects/alert.html.erb
<p>
  この被写体はすでに登録されています
</p>
<br>
<%= link_to 'この被写体の評価をする', "/subjects/#{params[:id]}/reviews/new" %>

app/views/subjects/index.html.erb
<div class="jumbotron">
  <h1>Jumbotron</h1>
  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>

            <ul>
              <% @subjects.each do |subject| %>
                <li>
                    <a href="/subjects/<%= subject.id %>">
                      <% if subject.images.present? %>
                        <%= image_tag(subject.images.order('created_at ASC').first.image_file.url, :size=> "480x390") %>
                      <% end %>
                    <h3><%= subject.name %></h3></a>
                    <% if subject.reviews.present? %>
                      <span class="rate rate<%= (subject.reviews.average(:rate).round(1) * 10).floor %>"></span>
                    <% end %>
                </li>
              <% end %>
              </ul>

                <form accept-charset="utf-8" action="/" method="get">
                </form>

app/views/subjects/new.html.erb
<%= form_for @subject do |f| %>
  <%= f.text_field :name, placeholder: "被写体の名前を入力してください" %>
  <%= f.select :prefecture, @prefectures.map{|prefec| prefec.name}, placeholder: "都道府県を選択" %>
  <%= f.submit "次へ" %>
<% end %>

app/views/subjects/search.html.erb
            <% if @subjects.present? %>
              <ul>
                <% @subjects.each do |subject| %>
                  <li>
                    <a href="/subjects/<%= subject.id %>" title="<%= subject.name %>">
                            <div style="background-image: url('http://find-travel.cdn-dena.com/picture/articlebody/84215');" title="<%= subject.name %>"></div>
                          <h3>
                            <span><%= subject.name %></span>
                          </h3>
                    </a>
                  </li>
                <% end %>
              </ul>
            <% else %>
                <p>
                  キーワードに当てはまる被写体はありません。
                </p>
                <a href="/subjects/new">被写体を登録する</a>
            <% end %>

app/views/subjects/show.html.erb
            <div>
              <header>
                <h2>
                  <%= @subject.name %>
                </h2>
                  <% if @subject.reviews.present? %>
                    <span class="rate rate<%= (@subject.reviews.average(:rate).round(1) * 10).floor %>"></span>
                  <% end %>
              </header>
              <div style="text-align: right">
                <a href="/subjects/<%= @subject.id %>/reviews/new">この被写体の評価をする</a>
              </div>


            <P>
              MAP
            </P>

            <div style='width: 800px;'>
              <div id="map" style='width: 800px; height: 400px;'></div>
            </div>

            <script type="text/javascript">
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                  markers = handler.addMarkers(<%=raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  handler.getMap().setCenter(new google.maps.LatLng(<%= @map.latitude %>, <%= @map.longitude %>));
                  handler.getMap().setZoom(15);
                });
            </script>


              <header>
                <h2>
                  みんなのレビュー
                </h2>
              </header>
              <% if @subject.reviews.present? %>
                <ul style="padding: 0">

                 <%= render partial: "review", collection: @subject.reviews %>

                </ul>

              <!-- レビューがまだ存在しない場合 -->
              <% else %>
                <p>
                  まだレビューはありません
                </p>
              <% end %>
            </div>

app/views/users/show.html.erb
<h2>
  <%= current_user.nickname %>さんのマイページ
</h2>
</br>
</br>


<h3>
  <%= current_user.nickname %>さんのレビュー
</h3>
<ul>
  <% current_user.reviews.each do |review| %>
    <li>
      <%= review.subject.name %>
    </li>
    <li>
      <a href="/subjects/<%= review.subject_id %>/reviews/<%= review.id %>/edit">レビューを修正する</a>
    </li>
  <% end %>
</ul>
</br>

<h3>
  <%= current_user.nickname %>さんのフォトギャラリー
</h3>
<ul>
  <% current_user.images.each do |image| %>
    <li>
      <%= image_tag image.image_file %>
    </li>
    <% if image.image_file2 != "" %>
      <li>
      <%= image_tag image.image_file2 %>
      </li>
    <% elsif image.image_file3 != "" %>
      <li>
      <%= image_tag image.image_file3 %>
      </li>
    <% end %>
  <% end %>
</ul>